### ISSUE TITLE
Delta Sink for Apache Flink

### ISSUE THREAD

**Issue by dennyglee** [delta-io/connectors#111]
Build a Flink/Delta sink (i.e., Flink writes to Delta Lake) potentially leveraging the Delta Standalone Writer per #85.   This issue expands on #74 

This work is currently in progress. Here are a list of tasks that need to be completed. 

- [x] Basic sink and writer framework - #196 and #213 
- [x] Committable generation with ids needed for txn guarantees - #220 
- [ ] Committing to the Delta table with txn guarantees - #224 
- [ ] Schema validation and migration
- [ ] Partitioning support
- [ ] Package name fixes
- [ ] Documentation
- [ ] Finalize sink public API
- [ ] Fix Maven artifact generation

**Comment by nicknezis** [comment]
I would be very interested in this. I've had similar thoughts for an Apache Heron sink. Perhaps we could collaborate on this feature?

**Comment by dennyglee** [comment]
Sure @nicknezis - perhaps create a new issue specific to Apache Heron and we can find some time to chat about this?

**Comment by nicknezis** [comment]
Thank you Denny. I've created #121 and #122 to capture the Heron equivalent issues.

**Comment by tdas** [comment]
Hello @chenzl-nhlab thank you for your interest! The check list in this ticket shows the tasks left, but most of them are already in progress by @pkubit-g Would be interested in testing out the flink connector?

**Comment by chenzl-nhlab** [comment]
Thank you for your reply! @tdas  I would like to do this.  What functions need to be tested?

**Comment by SteNicholas** [comment]
@dennyglee, @tdas , I come from Flink community and also have interest in Flink and Delta. Which tasks have not been completed?

**Comment by tdas** [comment]
@SteNicholas I tasks tied to the Sink have already been competed. The major piece we are working on is Table API and Catalog support (#250 and #389).
